/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.Controller;
import Model.Query;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class Invoice extends javax.swing.JPanel {

    Controller controller;
    Query q = new Query();
    public Invoice(Controller controller) {
        this.controller = controller;
        setBounds(0, 0, 800, 600);
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listTable = new javax.swing.JTable();
        name = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        searchBt = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        addressTxt = new javax.swing.JTextArea();
        date = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        totalPrice = new javax.swing.JTextField();
        sumTotal = new javax.swing.JButton();
        submit = new javax.swing.JButton();
        back = new javax.swing.JButton();
        addList = new javax.swing.JButton();
        addList1 = new javax.swing.JButton();
        nameCombo = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(153, 255, 153));
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("2005_iannnnnGMO", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ใบสั่งของ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMaximumSize(new java.awt.Dimension(800, 600));
        jPanel2.setMinimumSize(new java.awt.Dimension(800, 600));
        jPanel2.setPreferredSize(new java.awt.Dimension(800, 450));

        listTable.setFont(new java.awt.Font("2005_iannnnnGMO", 0, 24)); // NOI18N
        listTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "รายการ", "สี", "หน่วย", "จำนวน", "ราคาต่อหน่วย", "ราคารวม"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        listTable.setRowHeight(20);
        listTable.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                listTableAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        listTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                listTableMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(listTable);
        if (listTable.getColumnModel().getColumnCount() > 0) {
            listTable.getColumnModel().getColumn(0).setResizable(false);
            listTable.getColumnModel().getColumn(1).setResizable(false);
            listTable.getColumnModel().getColumn(1).setPreferredWidth(20);
            listTable.getColumnModel().getColumn(2).setResizable(false);
            listTable.getColumnModel().getColumn(2).setPreferredWidth(20);
            listTable.getColumnModel().getColumn(3).setResizable(false);
            listTable.getColumnModel().getColumn(3).setPreferredWidth(30);
            listTable.getColumnModel().getColumn(4).setResizable(false);
            listTable.getColumnModel().getColumn(5).setResizable(false);
        }

        name.setFont(new java.awt.Font("2005_iannnnnGMO", 0, 24)); // NOI18N
        name.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        name.setText("ชื่อ");

        jLabel3.setFont(new java.awt.Font("2005_iannnnnGMO", 0, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("วันที่");

        searchBt.setFont(new java.awt.Font("2005_iannnnnGMO", 0, 24)); // NOI18N
        searchBt.setText("ค้นหาที่อยู่");
        searchBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("2005_iannnnnGMO", 0, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("ที่อยู่");

        addressTxt.setColumns(20);
        addressTxt.setFont(new java.awt.Font("2005_iannnnnGMO", 0, 24)); // NOI18N
        addressTxt.setRows(5);
        jScrollPane2.setViewportView(addressTxt);

        date.setFont(new java.awt.Font("2005_iannnnnGMO", 0, 24)); // NOI18N

        jLabel5.setFont(new java.awt.Font("2005_iannnnnGMO", 0, 24)); // NOI18N
        jLabel5.setText("ราคา");

        totalPrice.setFont(new java.awt.Font("2005_iannnnnGMO", 0, 24)); // NOI18N

        sumTotal.setFont(new java.awt.Font("2005_iannnnnGMO", 0, 24)); // NOI18N
        sumTotal.setText("คำนวณ");
        sumTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumTotalActionPerformed(evt);
            }
        });

        submit.setFont(new java.awt.Font("2005_iannnnnGMO", 0, 24)); // NOI18N
        submit.setText("เสร็จสิ้น");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        back.setFont(new java.awt.Font("2005_iannnnnGMO", 0, 24)); // NOI18N
        back.setText("<< ย้อนกลับ");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        addList.setFont(new java.awt.Font("2005_iannnnnGMO", 0, 24)); // NOI18N
        addList.setText("เพิ่มสินค้า");
        addList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addListActionPerformed(evt);
            }
        });

        addList1.setFont(new java.awt.Font("2005_iannnnnGMO", 0, 24)); // NOI18N
        addList1.setText("ลบสินค้า");
        addList1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addList1ActionPerformed(evt);
            }
        });

        nameCombo.setFont(new java.awt.Font("2005_iannnnnGMO", 0, 24)); // NOI18N
        nameCombo.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                nameComboAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                            .addComponent(date)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(back)
                                .addGap(171, 171, 171))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(totalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(sumTotal))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(searchBt, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(addList)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addList1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(submit))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(name)
                            .addComponent(nameCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(searchBt)
                        .addGap(17, 17, 17)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(totalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sumTotal)
                            .addComponent(jLabel5)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(back)
                        .addComponent(addList)
                        .addComponent(addList1))
                    .addComponent(submit))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        List.s = new ArrayList<String>();
        controller.goToHome();
    }//GEN-LAST:event_backActionPerformed

    private void addListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addListActionPerformed
        controller.goTOSelect();
    }//GEN-LAST:event_addListActionPerformed

    private void addList1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addList1ActionPerformed
        DefaultTableModel model = (DefaultTableModel) listTable.getModel();
        model.removeRow(listTable.getSelectedRow());
    }//GEN-LAST:event_addList1ActionPerformed

    private void searchBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtActionPerformed
        String name = nameCombo.getSelectedItem().toString();
        String first = "";
        String last = "";
        for(int i=0;i<name.length();i++){
            if(name.charAt(i)==' '){
                break;
            }else{ 
                first += name.charAt(i);
            }
        }
        for(int i=name.length()-1;i<name.length();i--){
            if(name.charAt(i)==' '){
                break;
            }else{ 
                last = name.charAt(i) + last;
            }
        }
        ArrayList<String> s = q.searchForAddress(first, last);
        String address = s.get(0);
        String addressTemp = "";
        for(int i=0;i<address.length();i++){
            if(address.charAt(i)==' '){
                addressTemp +="\n";
            }else{ 
                addressTemp += address.charAt(i);
            }
        }
        addressTxt.setText(addressTemp);
    }//GEN-LAST:event_searchBtActionPerformed

    private void nameComboAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_nameComboAncestorAdded
        ArrayList<String> s = q.Customers();
        for(int i=0; i<s.size(); i+=6){
            nameCombo.addItem(s.get(i+1) + " " + s.get(i+2));
        }
    }//GEN-LAST:event_nameComboAncestorAdded

    private void listTableAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_listTableAncestorAdded
        DefaultTableModel model = (DefaultTableModel) listTable.getModel();
        ArrayList<String> s = List.s;
        for(int i=0;i < s.size();i+=4) {
            model.addRow(new Object[]
            {
                s.get(i),
                s.get(i+1),
                s.get(i+3),
                "",
                s.get(i+2),
                ""
            });
        }
    }//GEN-LAST:event_listTableAncestorAdded

    private void listTableMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listTableMouseReleased
        int row = listTable.getSelectedRow();
        String amoStr = (String) listTable.getValueAt(row, 3);
        double amo = 0;
        try {
            if(amoStr != null) {
                amo = Double.parseDouble(amoStr);
            }
            double price = Double.parseDouble((String) listTable.getValueAt(row, 4));
            double result = amo*price;
            listTable.setValueAt(result, row, 5);
        } catch(Exception e) {
            
        }
    }//GEN-LAST:event_listTableMouseReleased

    private void sumTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumTotalActionPerformed
        int rowSize = listTable.getRowCount();
        double sum = 0;
        for(int i = 0;i< rowSize;i++) {
            sum += (double)listTable.getValueAt(i, 5);
        }
        totalPrice.setText(""+sum);
    }//GEN-LAST:event_sumTotalActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
        String name = nameCombo.getSelectedItem().toString();
        String first = "";
        String last = "";
        for(int i=0;i<name.length();i++){
            if(name.charAt(i)==' '){
                break;
            }else{ 
                first += name.charAt(i);
            }
        }
        for(int i=name.length()-1;i<name.length();i--){
            if(name.charAt(i)==' '){
                break;
            }else{ 
                last = name.charAt(i) + last;
            }
        }
        
        if(addressTxt.getText().equals("")){
            JOptionPane.showMessageDialog(null,"กรุณากรอกที่อยู่!");
        }else if(date.getText().equals("")){
            JOptionPane.showMessageDialog(null,"กรุณวันกรอกที่ต้องการส่ง!");
        }else if(totalPrice.getText().equals("")){
            JOptionPane.showMessageDialog(null,"กรุณากดปุ่ม'คำนวณ'เพื่อแสดงยอด!");
        }else if(listTable.getRowCount()==0){
            JOptionPane.showMessageDialog(null,"กรุณาเพิ่มสินค้า!");
        }else{
            
            q.addInvoid(first, last, addressTxt.getText(), date.getText(), totalPrice.getText());

            String lastInvoid = q.lastestInvoid();
            int rowSize = listTable.getRowCount();
            for(int i = 0, j = 0 ; i < rowSize ; i++){
                String proName = (String)listTable.getValueAt(i, j);
                String color = (String)listTable.getValueAt(i, j+1);
                String unit = (String)listTable.getValueAt(i, j+2);
                String amo = (String)listTable.getValueAt(i, j+3);
                String perAmo = (String)listTable.getValueAt(i, j+4);
                String cost = Double.toString((double) listTable.getValueAt(i, j+5));
                q.addInvoidDetail(lastInvoid, proName, color, unit, amo, perAmo, cost);
            }
            List.s = new ArrayList<String>();
            JOptionPane.showMessageDialog(null,"เรียบร้อยแล้วครับ/ค่ะ!");
            controller.goTOInvoiceList();
        }
    }//GEN-LAST:event_submitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addList;
    private javax.swing.JButton addList1;
    private javax.swing.JTextArea addressTxt;
    private javax.swing.JButton back;
    private javax.swing.JTextField date;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable listTable;
    private javax.swing.JLabel name;
    private javax.swing.JComboBox<String> nameCombo;
    private javax.swing.JButton searchBt;
    private javax.swing.JButton submit;
    private javax.swing.JButton sumTotal;
    private javax.swing.JTextField totalPrice;
    // End of variables declaration//GEN-END:variables
}
